[package]
name                    =  "uide"
version                 =  "0.0.1"
description             =  "old-fashioned IDE with minimal CPU/RAM requirements"
authors                 = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license                 =  "MIT"
repository              =  "https://github.com/ponyatov/uide"
edition                 =  "2024"

[[bin]]
name                    = "main"
path                    = "src/main.rs"

[[bin]]
name                    = "server"
path                    = "src/server.rs"

[dependencies]
const_format            = "0.2"

## GUI
druid                   = "0.8"
# piet = "0.8"
# piet-common = "0.8"

## IDE features
# syntect = "5.0.0"       # подсветка синтаксиса
# ropey = "1.6.0"         # текстовая структура
# lsp-types = "0.94.0"    # LSP поддержка
# toml = "0.8.2"          # конфигурация
# notify = "5.2.0"        # отслеживание файлов

[target.'cfg(target_os = "linux")'.dependencies]
libc                    = "0.2"
memmap2                 = "0.9"
piet-cairo              = "0.8"

[features]
pc                      = ["i5"]
i5                      = ["x86_64"]
x86_64                  = ["linux"]
linux                   = []
